# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    resolvers:
        profile_photos:
            web_path:
                # use %kernel.project_dir%/web for Symfony prior to 4.0.0
                web_root: "%kernel.project_dir%/public"
                cache_prefix: "media/cache"
    filter_sets:
        ImgPublicLoad:
            quality: 80
            filters:
                thumbnail:
                    size: [ 600, 500 ]
                    mode: outbound
                watermark:
                # chemin vers le fichier
                    image: ../public/publication/img/wazzup.png
                # Taille relative de l'image
                    size: 0.2
                # set the position of the watermark
                    position: bottomright
        reduc:
            quality: 85
            filters:
                scale:
                    dim: [ 600, 500 ]
                    watermark:
                        # chemin vers le fichier
                        image: ../public/collab/wazzup.png
                        # Taille relative de l'image
                        size: 1
                        # set the position of the watermark
                        position: bottomright

#        WaTerMark:
#            quality: 80
#                filters:
#                    upscale:
#                        min: [ 600, 500 ]
#                    thumbnail:
#                        size: [ 600, 500 ]
#                        mode: outbound
#                    watermark:
#                        # chemin vers le fichier
#                        image: ../public/collab/wazzup.png
#                        # Taille relative de l'image
#                        size: 0.1
#                        # set the position of the watermark
#                        position: bottomright
