#index:
#    path: /
#    controller: App\Controller\DefaultController::index
notfound:
    path: /404
    controller: App\Controller\ErrorpageController::index
captcha_routing:
  resource: "@CaptchaBundle/Resources/config/routing.yml"
    